# Claude API
ANTHROPIC_API_KEY = "sk-ant-api03-..."

# Arize Phoenix for observability
ARIZE_SPACE_ID = "your-space-id"
ARIZE_API_KEY = "your-arize-key"

# Application settings
DEBUG_MODE = true
LOG_LEVEL = "INFO"